### ISSUE TITLE
Question: can you limit trailers to only what's in your library?

### ISSUE THREAD

**Issue by snakeeyes5** [fbacher/Kodi-script.video.randomtrailers#12]
I'd like to limit the trailers it pulls for only movies that are in my library. It's kind of a tease to play a trailer for a movie I don't have, so rather only play trailers for movies that I have but haven't watched yet/recently?

Great add-on, has come a long way over the last 6 months.

**Comment by fbacher** [comment]
Yes, you can. Go to Settings -> My add-ons -> Video add-ons -> Random Trailers 
Select Configure. On the tab "Library" Decide if you don't want remote trailers to be downloaded for any of your local movies.
On the tab "Remote Trailers" Decide if you want anything other than trailers for any remotely downloaded 'trailers' (from the previous step)
On the tab "Themoviedb.org" Disable "include Trailers from Themoviedb.org
On the tab "TFH" Disable "Include Trailers from Hell"

That should do it.

**Comment by snakeeyes5** [comment]
Just to be clear, I don't have any trailers in my library. I was hoping it would download trailers for movies I actually have from TMDB.  I've tried changing the settings and couldn't get it to work, it just kept downloading trailers for random movies I don't have.

**Comment by baddie1** [comment]
I use tinyMediaManager to download the trailers for all of my movies, they are saved in the folders with the other movie info. then Randomtrailers plays them.

**Comment by fbacher** [comment]
If you want RandomTrailers to download trailers from TMDb for your local movies, then:
On the tab "Library" select:
* Include Trailers from Library
* Include movies with remote trailers
* Include movies with no Trailer Info
That should do it.
TMDb is used to find the trailers, it won't look elsewhere
The trailers will NOT be copied over into your library space and made known to Kodi (as a trailer for a particular movie). You can manually do this if you like.
By default, the downloaded trailers will be placed into the cache (See the tab labeled "Cache", it should be enabled by default.). If the cache is not enabled, then the trailers are downloaded each time they are played.

If at some point you want to copy the downloaded trailers, you can easily find them in the cache (by default in <kodi>/userdata/addon_data/script.video.randomtrailers/cache/). The file names are pretty obvious, but you have to copy them one at a time. Your mileage on quality will vary.

**Comment by snakeeyes5** [comment]
Thanks, @baddie1 - I'll try out tinyMediaManager and see how I like it.

@fbacher I tried those exact settings and it plays trailers for movies I don't have.  Letter from an Unknown Woman (1948). I've yet to see it play a trailer of a movie I actually have.

**Comment by fbacher** [comment]
I'll look into it. I expect it to take some time since it crawls through your library and queries TMDb for each one, and it intentionally limits how frequently it queries.

**Comment by fbacher** [comment]
Opened Issue #13 to resolve the bug identified here

**Comment by snakeeyes5** [comment]
Thanks, willing to help test, just let me know
